---
language: python
python:
  - "2.7"
  - "3.4"
install:
  - "pip install -r requirements-dev.txt"
  - "pip install coveralls"
script: "py.test --cov=pryvate"
after_script: "pre-commit run --all-files"
after_success:
  - coveralls
